version: "3"
services:
  db:
    image: "mysql:8.0.31"
    container_name: albumreviewsdb
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'albumreviews-dev'
      MYSQL_USER: albumreviews
      MYSQL_PASSWORD: 'password'
    restart: unless-stopped
    volumes:
      - sqlvolume:/var/opt/mysql
    ports:
      - "3306:3306"
    expose:
      - '3306'

volumes: 
  sqlvolume:
  

